### ISSUE TITLE
Update README file with instructions on setting up project locally

### ISSUE THREAD

**Issue by clevetong** [ANU-Student-Connect/student-connect-2024S2#10]
Update the README file with an introduction to the web page, installation guide, configuration, and other related documents and details.

[README](https://github.com/ANU-Student-Connect/student-connect/blob/main/README.md)

**Comment by CloudyRowly** [comment]
Good, just a small typo which has been fixed. May need to add initial requirements e.g. how to install npm but we will see how it goes first
