### ISSUE TITLE
Complete Audit 1 Feedback Analysis

### ISSUE THREAD

**Issue by ahmadMusawi** [ANU-Student-Connect/student-connect-2024S2#27]
- Complete audit 1 feedback review.
- Any feedback needs to be assigned to a member (or members) unless the team needs to decide what to do. In this case, it needs to be added to the agenda for the next group meeting to be discussed.

[Audit 1 Feedback Analysis](https://docs.google.com/document/d/1pw1xdFWuWWZNV_Ih_jFDG0Jqw-gfzUCTVty6twBFZ4w/edit)

**Comment by ahmadMusawi** [comment]
Complete audit 1 feedback review.
Any feedback needs to be assigned to a member  (or members) unless the team needs to decide what to do. In this case, it needs to be added to the agenda for the next group meeting to be discussed.

**Comment by CloudyRowly** [comment]
All good!
