### ISSUE TITLE
Research on database technology

### ISSUE THREAD

**Issue by ahmadMusawi** [ANU-Student-Connect/student-connect-2024S2#29]
- Research on different database technologies
- Explain the pros and cons of each against each other
- Make recommendation(s) on what technologies should be selected
- Detail the pros and cons of the recommendation(s)

**Comment by ahmadMusawi** [comment]
Please find the research completed in the project Google Drive under Documents.

[Database Technology Reserach](https://docs.google.com/document/d/1muH8DbBKnacH23f2zqUjfTKEtsWoHYbK/edit)

**Comment by CloudyRowly** [comment]
document exists, decisions has been made well before the time of upload but its good for future reference.
