### ISSUE TITLE
Figma: Animate P2P page

### ISSUE THREAD

**Issue by CloudyRowly** [ANU-Student-Connect/student-connect-2024S2#42]
Animate and link any possible elements.

Interact-able elements should have effects upon clicking on e.g. buttons upon clicking on should have ripple effect, then route to the destination page.

If page is long/scrollable, make it scrollable with place-holding content.

[figma page](https://www.figma.com/design/aCkZ3X0RHvlKy2MWNdicJX/Student-Connect?node-id=601-10&t=S8gxnHhwqCPhkSQJ-1)

**Comment by CloudyRowly** [comment]
Added some missing connections to other tabs. The animation for this part is very detailed, good job!

**Comment by nicelyhorse** [comment]
The "home" button upside directs to the Home page and the user avatar on the right hand upside directs to the User Profile Page, so that the other pages could be connected through these two pages
