### ISSUE TITLE
Populate database with testing data

### ISSUE THREAD

**Issue by CloudyRowly** [ANU-Student-Connect/student-connect-2024S2#51]
Populate database with some data entries to test the platform.

Criteria:

- All entries must have logical, reasonable values & attributes
- At least 10 entries must capture user personas, these entries must be closest to real users and real use cases
- Data must be in a testing environment, such that this environment can exist even after deployed (So we can have a testing and deployed environment concurrently)
- Make ~200-300 entries (or a suitable amount)

**Comment by CloudyRowly** [comment]
@HoangNhienPhan Please update progress of this issue, thank you!

**Comment by HoangNhienPhan** [comment]
Done. Regarding the third point in your requirement, I think currently we are working on the test database. We can easily create a database to use for actual deployment and modify the link to the database in our env file to make our code connect to the deployed database or the test database as we wish.
