### ISSUE TITLE
Research user persona

### ISSUE THREAD

**Issue by CloudyRowly** [ANU-Student-Connect/student-connect-2024S2#52]
Based on the data from the market survey, create main types of users who are going to be using the platform, match them against the features so team gains a better understanding of the user use case

Create a doc in team's Drive, put link here. Do this before issue #51.

**Comment by CloudyRowly** [comment]
@HoangNhienPhan Please update the status of this issue, thank you!

**Comment by HoangNhienPhan** [comment]
This is the link to the user personas document: https://docs.google.com/document/d/1O1_jjfFa0LUkkaZC9UnMGGnPyioyv2sTRZf0U0lqbgQ/edit?usp=sharing
