### ISSUE TITLE
Compose video script

### ISSUE THREAD

**Issue by CloudyRowly** [ANU-Student-Connect/student-connect-2024S2#59]
Make script for video.

Must show:

- Context of the problem (some statistics from universities around the world) (Minh)
- Scope of problem or opportunity (refer to SWOT analysis) (Oliver)
- Approach or solution (Quick summary of project) (Oliver)
- Impact of project (to student) (Minh)

[Instruction for video](https://comp.anu.edu.au/TechLauncher/current_students/evaluation/project_video/)

[Link to Script Google Doc](https://docs.google.com/document/d/1TBLBUS1ZAAYiMkfUXhHBVutAkSOKENbbM_Olf8PoDic/edit?usp=sharing)

**Comment by nicelyhorse** [comment]
Minh, how is the work divided in this script, Is that I do two of the tasks and you do the other two？

**Comment by nicelyhorse** [comment]
Hi Minh, I've finished the two assigned script parts could you please check that, if there is any problems that I should fix please let me know, thanks!

**Comment by CloudyRowly** [comment]
I have reviewed the texts and revised them accordingly.
