### ISSUE TITLE
Poster for the showcase

### ISSUE THREAD

**Issue by ahmadMusawi** [ANU-Student-Connect/student-connect-2024S2#62]
Create a poster for the showcase. 

- The poster should include the following:
- Introducing the project
- Stating the problem
- Solution and Approach
- Introducing the team
- QR code to the team's showcase video

**Comment by CloudyRowly** [comment]
Poster seems a little blurry when just zoomed in a little, is it A0? Also, consider the text size when it is printed out in A0, and remove the 3 pink highlights.

If texts are too big for A0, make it smaller and add some icons/representations of basic features of the platform.

Also, rephrase "ANU authentication" to something more common English: "ANU student community exclusive"
