### ISSUE TITLE
Initialize Project, CI/CD setup

### ISSUE THREAD

**Issue by clevetong** [ANU-Student-Connect/student-connect-2024S2#9]
Initialize a new Node.js project repository with the necessary configuration files. Set up the basic project structure. Configure CI tools (Github Actions) for automated testing, and set up CD pipeline for automated deployment using Docker. Set up a test server using Google Cloud. 

Edit:
**Use Student Connect's admin mail to setup required 3rd party services**

**Comment by CloudyRowly** [comment]
Please make a comprehensive, detailed description for the issue by listing out what technical tasks need to be done.

**Comment by clevetong** [comment]
> Please make a comprehensive, detailed description for the issue by listing out what technical tasks need to be done.

Completed.

**Comment by CloudyRowly** [comment]
Let's discuss the Google cloud, Docker accounts and API a little before we move on. Check DM for meeting allocation.

**Comment by CloudyRowly** [comment]
Move Google Cloud and Docker to group's admin mail account.

**Comment by clevetong** [comment]
Hosting our app using Google Cloud Build seems not working because our front and backend are running in different docker containers, as a result of the separation of frontend and backend. I'll try other deployment options. One possible choice is to run our docker-compose network in Google VM.

**Comment by clevetong** [comment]
The initial setup of the project repository and the CI/CD is done. The deployment option restrains the CI/CD. I'll create a new issue to debug.
